POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Intel Core i7 - 10400k",
  "price": 2599.99
}


###
GET http://localhost:8080/products
Content-Type: application/json

###
GET http://localhost:8080/products/f6d62975-2a0d-4b02-859e-b4ecdab0730d

###
PUT http://localhost:8080/products/64bf7f96-825c-487a-a722-a083c4d83aa7
Content-Type: application/json

{
  "name": "Caneta Preta",
  "price": 4.25
}

###
DELETE http://localhost:8080/products/793cf105-4783-4931-ba55-c741784e7dce
